primary_topics:
  - power_market
  - storage
  - American stock market
  - ai
  - semiconductor
  - macro
  - interest_rate
  - invest
  - cryptocurrenvy

boost_keywords:
  - 储能
  - 电力市场
  - 现货
  - 电力交易
  - 交易
  - 量化
  - 数字货币
  - AI
  - inference
  - GPU
  - 芯片
  - 半导体
  - 利率
  - 通胀
  - 投资
  - 美股

negative_keywords:
  - News
  - sports
  - celebrity
  - lifestyle
  -
  -

important_people:
  - Jensen Huang
  - Sam Altman
  - Elon Musk
  - 孟岩
  - 李继刚